version: "3.8"
services:
  frontend:
    container_name: aleela-ovrd-frontend
    build: .
    restart: always #change if you don't want your container restarting
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
